// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dagiygtjfpwdslngihlj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhZ2l5Z3RqZnB3ZHNsbmdpaGxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMDUwNjEsImV4cCI6MjA3MTc4MTA2MX0.QCTYNjtE2qPkQRWNvgXtQTk6OOVeXPWxm281spY1T5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});